### ISSUE TITLE
请求国服作业的格式适配

### ISSUE THREAD

**Issue by Eurika-create** [AtmoOmen/ffxiv_visland-cn#10]
无人岛进入百周循环阶段，作业格式发生变更，请求适配

D1:休息
--
D2:3×厨刀、鲨油、厨刀、鲨油
D2:1×水牛豆沙拉、厨刀、水牛豆沙拉、厨刀、鲨油
D3:3×水牛豆沙拉、鳞指套、水牛豆沙拉、鳞指套
D3:1×绳索、床、绳索、床
D4:3×玉米片、腌小萝卜、玉米片、腌小萝卜
D4:1×木刷、云杉圆盾、木刷、云杉圆盾
D5:3×辣椒粉、植物成长剂、辣椒粉、植物成长剂
D5:1×兽牙耳坠、绵羊地毯、韭葱洋葱汤、植物成长剂
D6:休息
D7:3×火药、石榴石刺剑、火药、石榴石刺剑
D7:1×兽牙耳坠、白银耳夹、兽牙耳坠、白银耳夹

如果能自动调整休息日就再好不过了

**Comment by AtmoOmen** [comment]
已更新

**Comment by Eurika-create** [comment]
处理猫耳小员委托的求解器还是有用的，大佬能给加回来不
